### ISSUE TITLE
Could not lookup value for field io.fabric8.openshift.api.model.DeploymentConfig io.syndesis.systests.DeploymentTest.ui

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-system-tests#18]
System tests are failing with:

    Tests in error: 
      restShouldBeReady(io.syndesis.systests.DeploymentTest): Could not lookup value for field io.fabric8.openshift.api.model.DeploymentConfig io.syndesis.systests.DeploymentTest.ui
      uiShouldBeReady(io.syndesis.systests.DeploymentTest): Could not lookup value for field io.fabric8.openshift.api.model.DeploymentConfig io.syndesis.systests.DeploymentTest.ui
      keycloakShouldBeReady(io.syndesis.systests.DeploymentTest): Could not lookup value for field io.fabric8.openshift.api.model.DeploymentConfig io.syndesis.systests.DeploymentTest.ui

Cause seems to be:

    Caused by: java.lang.NullPointerException
    	at org.arquillian.cube.kubernetes.impl.enricher.AbstractKubernetesResourceProvider.toUsersResource(AbstractKubernetesResourceProvider.java:52)
    	at org.arquillian.cube.openshift.impl.enricher.external.DeploymentConfigResourceProvider.lookup(DeploymentConfigResourceProvider.java:23)
    	at org.jboss.arquillian.test.impl.enricher.resource.ArquillianResourceTestEnricher.lookup(ArquillianResourceTestEnricher.java:130)
    	at org.jboss.arquillian.test.impl.enricher.resource.ArquillianResourceTestEnricher.enrich(ArquillianResourceTestEnricher.java:67)
    	... 98 more

See [build #9](https://jenkins-syndesis-ci.b6ff.rh-idev.openshiftapps.com/blue/organizations/jenkins/syndesis-rest/detail/master/9/pipeline) onwards.

Not sure about the root cause, but perhaps bumping arquillian-cube to 1.6.0 might help?

**Comment by zregvart** [comment]
fixed in #17
